
[workspace]

members = [
  "core",
  "cli",
  "lsp",
]

default-members = [
  "core",
]

[profile.release]
debug=1
opt-level=2
lto="thin"
incremental=true

[profile.dev]
opt-level=1
lto="thin"
incremental=true
