
[workspace]

members = [
  "core",
  "cli",
  "lsp",
  "opentheory",
  "jupyter"
]

default-members = [
  "core",
]

[profile.release]
debug=1
opt-level=2
#lto="thin"
lto="off"

[profile.dev]
opt-level=1
lto="off"
