
%token EOI
%token <string> IDENT COLON_STR QUOTED_STR INT
%token VAR LET SEMI EQUAL COMMA WHILE BREAK CONTINUE RETURN
%token FN EVAL
%token LPAREN RPAREN LBRACKET RBRACKET LBRACE RBRACE
%token PLUS MINUS STAR SLASH LT LEQ GT GEQ

%%
