
%token EOI
%token <string> IDENT SYMBOL COLON_STR QUOTED_STR INT
%token LAMBDA WITH DOT COLON DOLLAR DOLLAR_LBRACE
%token VAR LET SEMI EQUAL COMMA WHILE IF ELSE BREAK CONTINUE RETURN
%token FN
%token LPAREN RPAREN LBRACKET RBRACKET LBRACE RBRACE
%token PLUS MINUS STAR SLASH LT LEQ GT GEQ EQ NEQ AND OR NOT

%%
