[package]
name = "trustee-stubs"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]
edition = "2018"
[lib]
crate-type = ["staticlib", "cdylib"]


[dependencies]
trustee = {path = "/home/simon/w/trustee/", version = "*"}
ocaml = "^0.12.4"
